const dotenv = require("dotenv");
dotenv.config();

const connectDB = require("./src/config/db");
const Question = require("./src/model/question");

const questions = [
  {
    title: "Two Sum",
    slug: "two-sum",
    difficulty: "Easy",
    description: "Given an array of integers and a target value, return the indices of the two numbers that add up to the target.",
    examples: ["Example: nums = [2,7,11,15], target = 9 -> [0,1]"],
    constraints: ["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nvector<int> twoSum(vector<int>& nums, int target) {\n  return {};\n}\n",
      Java: "class Solution { public int[] twoSum(int[] nums, int target) { return new int[] {}; } }",
      Python: "def two_sum(nums, target):\n    return []\n",
      JavaScript: "function twoSum(nums, target) {\n  return [];\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "2 7 11 15\n9", expectedOutput: "0 1", isHidden: false }],
    hiddenTestCases: [{ input: "3 3\n6", expectedOutput: "0 1", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["array", "hash-map"],
  },
  {
    title: "Reverse String",
    slug: "reverse-string",
    difficulty: "Easy",
    description: "Reverse the characters in a string.",
    examples: ["Example: hello -> olleh"],
    constraints: ["1 <= s.length <= 10^5"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nstring reverseString(string s) { return s; }\n",
      Java: "class Solution { public String reverseString(String s) { return s; } }",
      Python: "def reverse_string(s):\n    return s\n",
      JavaScript: "function reverseString(s) {\n  return s;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "hello", expectedOutput: "olleh", isHidden: false }],
    hiddenTestCases: [{ input: "racecar", expectedOutput: "racecar", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["string"],
  },
  {
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    difficulty: "Medium",
    description: "Check whether a given string of parentheses is valid.",
    examples: ["Example: ()[]{} -> true"],
    constraints: ["1 <= s.length <= 10^4"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nbool isValid(string s) { return false; }\n",
      Java: "class Solution { public boolean isValid(String s) { return false; } }",
      Python: "def is_valid(s):\n    return False\n",
      JavaScript: "function isValid(s) {\n  return false;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "()[]{}", expectedOutput: "true", isHidden: false }],
    hiddenTestCases: [{ input: "(]", expectedOutput: "false", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["stack", "string"],
  },
  {
    title: "Merge Two Sorted Lists",
    slug: "merge-two-sorted-lists",
    difficulty: "Medium",
    description: "Merge two sorted linked lists into one sorted list.",
    examples: ["Example: [1,2,4] and [1,3,4] -> [1,1,2,3,4,4]"],
    constraints: ["The number of nodes in both lists is in the range [0, 50]"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nstruct ListNode { int val; ListNode *next; ListNode(int x): val(x), next(nullptr) {} };\nListNode* mergeTwoLists(ListNode* l1, ListNode* l2) { return l1; }\n",
      Java: "class Solution { public ListNode mergeTwoLists(ListNode l1, ListNode l2) { return l1; } }",
      Python: "def merge_two_lists(l1, l2):\n    return l1\n",
      JavaScript: "function mergeTwoLists(l1, l2) {\n  return l1;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "1 2 4\n1 3 4", expectedOutput: "1 1 2 3 4 4", isHidden: false }],
    hiddenTestCases: [{ input: "\n", expectedOutput: "", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["linked-list", "merge"],
  },
  {
    title: "Maximum Subarray",
    slug: "maximum-subarray",
    difficulty: "Medium",
    description: "Find the contiguous subarray with the largest sum.",
    examples: ["Example: [-2,1,-3,4,-1,2,1,-5,4] -> 6"],
    constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint maxSubArray(vector<int>& nums) { return 0; }\n",
      Java: "class Solution { public int maxSubArray(int[] nums) { return 0; } }",
      Python: "def max_sub_array(nums):\n    return 0\n",
      JavaScript: "function maxSubArray(nums) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "-2 1 -3 4 -1 2 1 -5 4", expectedOutput: "6", isHidden: false }],
    hiddenTestCases: [{ input: "1 2 3", expectedOutput: "6", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["array", "dynamic-programming"],
  },
  {
    title: "Best Time to Buy and Sell Stock",
    slug: "best-time-to-buy-and-sell-stock",
    difficulty: "Easy",
    description: "Given stock prices, find the maximum profit using one transaction.",
    examples: ["Example: [7,1,5,3,6,4] -> 5"],
    constraints: ["1 <= prices.length <= 10^5"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint maxProfit(vector<int>& prices) { return 0; }\n",
      Java: "class Solution { public int maxProfit(int[] prices) { return 0; } }",
      Python: "def max_profit(prices):\n    return 0\n",
      JavaScript: "function maxProfit(prices) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "7 1 5 3 6 4", expectedOutput: "5", isHidden: false }],
    hiddenTestCases: [{ input: "7 6 4 3 1", expectedOutput: "0", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["array", "greedy"],
  },
  {
    title: "Climbing Stairs",
    slug: "climbing-stairs",
    difficulty: "Easy",
    description: "Count the number of distinct ways to climb to the top of a staircase.",
    examples: ["Example: n = 2 -> 2"],
    constraints: ["1 <= n <= 45"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint climbStairs(int n) { return 0; }\n",
      Java: "class Solution { public int climbStairs(int n) { return 0; } }",
      Python: "def climb_stairs(n):\n    return 0\n",
      JavaScript: "function climbStairs(n) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "2", expectedOutput: "2", isHidden: false }],
    hiddenTestCases: [{ input: "5", expectedOutput: "8", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["dynamic-programming"],
  },
  {
    title: "Contains Duplicate",
    slug: "contains-duplicate",
    difficulty: "Easy",
    description: "Return true if the array contains any duplicate values.",
    examples: ["Example: [1,2,3,1] -> true"],
    constraints: ["1 <= nums.length <= 10^5"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nbool containsDuplicate(vector<int>& nums) { return false; }\n",
      Java: "class Solution { public boolean containsDuplicate(int[] nums) { return false; } }",
      Python: "def contains_duplicate(nums):\n    return False\n",
      JavaScript: "function containsDuplicate(nums) {\n  return false;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "1 2 3 1", expectedOutput: "true", isHidden: false }],
    hiddenTestCases: [{ input: "1 2 3 4", expectedOutput: "false", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["array", "set"],
  },
  {
    title: "Group Anagrams",
    slug: "group-anagrams",
    difficulty: "Medium",
    description: "Group words that are anagrams of each other.",
    examples: ["Example: [eat, tea, tan, ate, nat, bat] -> [[eat, tea, ate], [tan, nat], [bat]]"],
    constraints: ["1 <= strs.length <= 10^4", "0 <= strs[i].length <= 100"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nvector<vector<string>> groupAnagrams(vector<string>& strs) { return {}; }\n",
      Java: "class Solution { public List<List<String>> groupAnagrams(String[] strs) { return new ArrayList<>(); } }",
      Python: "def group_anagrams(strs):\n    return []\n",
      JavaScript: "function groupAnagrams(strs) {\n  return [];\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "eat tea tan ate nat bat", expectedOutput: "grouped", isHidden: false }],
    hiddenTestCases: [{ input: "a b", expectedOutput: "grouped", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["hash-map", "string"],
  },
  {
    title: "Longest Consecutive Sequence",
    slug: "longest-consecutive-sequence",
    difficulty: "Hard",
    description: "Find the length of the longest consecutive sequence in an unsorted array.",
    examples: ["Example: [100,4,200,1,3,2] -> 4"],
    constraints: ["0 <= nums.length <= 10^5"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint longestConsecutive(vector<int>& nums) { return 0; }\n",
      Java: "class Solution { public int longestConsecutive(int[] nums) { return 0; } }",
      Python: "def longest_consecutive(nums):\n    return 0\n",
      JavaScript: "function longestConsecutive(nums) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "100 4 200 1 3 2", expectedOutput: "4", isHidden: false }],
    hiddenTestCases: [{ input: "0", expectedOutput: "0", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["array", "set"],
  },
  {
    title: "Number of Islands",
    slug: "number-of-islands",
    difficulty: "Hard",
    description: "Count the number of islands in a grid of 0s and 1s.",
    examples: ["Example: [[1,1,0,0],[0,1,0,0],[0,0,1,1]] -> 3"],
    constraints: ["m, n <= 300"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint numIslands(vector<vector<char>>& grid) { return 0; }\n",
      Java: "class Solution { public int numIslands(char[][] grid) { return 0; } }",
      Python: "def num_islands(grid):\n    return 0\n",
      JavaScript: "function numIslands(grid) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "1 1 0 0\n0 1 0 0\n0 0 1 1", expectedOutput: "3", isHidden: false }],
    hiddenTestCases: [{ input: "0 0\n0 0", expectedOutput: "0", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["graph", "dfs"],
  },
  {
    title: "Kth Largest Element",
    slug: "kth-largest-element",
    difficulty: "Medium",
    description: "Find the kth largest element in an unsorted array.",
    examples: ["Example: [3,2,1,5,6,4], k = 2 -> 5"],
    constraints: ["1 <= k <= nums.length <= 10^4"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint findKthLargest(vector<int>& nums, int k) { return 0; }\n",
      Java: "class Solution { public int findKthLargest(int[] nums, int k) { return 0; } }",
      Python: "def find_kth_largest(nums, k):\n    return 0\n",
      JavaScript: "function findKthLargest(nums, k) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "3 2 1 5 6 4\n2", expectedOutput: "5", isHidden: false }],
    hiddenTestCases: [{ input: "1 2 3 4 5\n4", expectedOutput: "2", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["heap", "array"],
  },
  {
    title: "Palindrome Number",
    slug: "palindrome-number",
    difficulty: "Easy",
    description: "Determine whether an integer is a palindrome.",
    examples: ["Example: 121 -> true"],
    constraints: ["-2^31 <= x <= 2^31 - 1"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nbool isPalindrome(int x) { return false; }\n",
      Java: "class Solution { public boolean isPalindrome(int x) { return false; } }",
      Python: "def is_palindrome(x):\n    return False\n",
      JavaScript: "function isPalindrome(x) {\n  return false;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "121", expectedOutput: "true", isHidden: false }],
    hiddenTestCases: [{ input: "-121", expectedOutput: "false", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["math", "string"],
  },
  {
    title: "Longest Common Prefix",
    slug: "longest-common-prefix",
    difficulty: "Easy",
    description: "Find the longest common prefix among a list of strings.",
    examples: ["Example: [flower, flow, flight] -> fl"],
    constraints: ["0 <= strs.length <= 200", "0 <= strs[i].length <= 200"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nstring longestCommonPrefix(vector<string>& strs) { return \"\"; }\n",
      Java: "class Solution { public String longestCommonPrefix(String[] strs) { return \"\"; } }",
      Python: "def longest_common_prefix(strs):\n    return \"\"\n",
      JavaScript: "function longestCommonPrefix(strs) {\n  return \"\";\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "flower flow flight", expectedOutput: "fl", isHidden: false }],
    hiddenTestCases: [{ input: "dog racecar car", expectedOutput: "", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["string"],
  },
  {
    title: "Search Insert Position",
    slug: "search-insert-position",
    difficulty: "Medium",
    description: "Return the index where a target should be inserted into a sorted array.",
    examples: ["Example: [1,3,5,6], target = 5 -> 2"],
    constraints: ["1 <= nums.length <= 10^4"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint searchInsert(vector<int>& nums, int target) { return 0; }\n",
      Java: "class Solution { public int searchInsert(int[] nums, int target) { return 0; } }",
      Python: "def search_insert(nums, target):\n    return 0\n",
      JavaScript: "function searchInsert(nums, target) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "1 3 5 6\n5", expectedOutput: "2", isHidden: false }],
    hiddenTestCases: [{ input: "1 3 5 6\n2", expectedOutput: "1", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["binary-search", "array"],
  },
  {
    title: "First Bad Version",
    slug: "first-bad-version",
    difficulty: "Medium",
    description: "Find the first bad version using binary search.",
    examples: ["Example: versions = 5, bad = 4 -> 4"],
    constraints: ["1 <= bad <= n <= 2^31 - 1"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint firstBadVersion(int n) { return 0; }\n",
      Java: "class Solution { public int firstBadVersion(int n) { return 0; } }",
      Python: "def first_bad_version(n):\n    return 0\n",
      JavaScript: "function firstBadVersion(n) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "5 4", expectedOutput: "4", isHidden: false }],
    hiddenTestCases: [{ input: "1 1", expectedOutput: "1", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["binary-search"],
  },
  {
    title: "Single Number",
    slug: "single-number",
    difficulty: "Easy",
    description: "Find the single number that appears only once in an array where every other number appears twice.",
    examples: ["Example: [2,2,1] -> 1"],
    constraints: ["1 <= nums.length <= 3 * 10^4"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint singleNumber(vector<int>& nums) { return 0; }\n",
      Java: "class Solution { public int singleNumber(int[] nums) { return 0; } }",
      Python: "def single_number(nums):\n    return 0\n",
      JavaScript: "function singleNumber(nums) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "2 2 1", expectedOutput: "1", isHidden: false }],
    hiddenTestCases: [{ input: "4 1 2 1 2", expectedOutput: "4", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["bit-manipulation", "array"],
  },
  {
    title: "Container With Most Water",
    slug: "container-with-most-water",
    difficulty: "Medium",
    description: "Find two lines that together with the x-axis form a container that holds the most water.",
    examples: ["Example: [1,8,6,2,5,4,8,3,7] -> 49"],
    constraints: ["n == height.length", "2 <= n <= 10^5"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint maxArea(vector<int>& height) { return 0; }\n",
      Java: "class Solution { public int maxArea(int[] height) { return 0; } }",
      Python: "def max_area(height):\n    return 0\n",
      JavaScript: "function maxArea(height) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "1 8 6 2 5 4 8 3 7", expectedOutput: "49", isHidden: false }],
    hiddenTestCases: [{ input: "2 3 4 5 18 17 6", expectedOutput: "17", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["two-pointers", "array"],
  },
  {
    title: "Pow(x, n)",
    slug: "pow-x-n",
    difficulty: "Medium",
    description: "Implement pow(x, n), which calculates x raised to the power n.",
    examples: ["Example: x = 2.0, n = 10 -> 1024.0"],
    constraints: ["-100.0 < x < 100.0", "-2^31 <= n <= 2^31 - 1"],
    starterCode: {
      "C++": "#include <bits/stdc++.h>\nusing namespace std;\ndouble myPow(double x, int n) { return 0; }\n",
      Java: "class Solution { public double myPow(double x, int n) { return 0; } }",
      Python: "def my_pow(x, n):\n    return 0\n",
      JavaScript: "function myPow(x, n) {\n  return 0;\n}\n",
    },
    supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
    sampleTestCases: [{ input: "2.0 10", expectedOutput: "1024.0", isHidden: false }],
    hiddenTestCases: [{ input: "2.0 -2", expectedOutput: "0.25", isHidden: true }],
    timeLimit: 2000,
    memoryLimit: 256,
    tags: ["math", "recursion"],
  },
];

// If the list is shorter than 50, auto-generate placeholder questions
function appendPlaceholders(targetCount = 50) {
  const difficulties = ["Easy", "Medium", "Hard"];
  const start = questions.length + 1;
  for (let i = start; i <= targetCount; i++) {
    const difficulty = difficulties[(i - 1) % difficulties.length];
    questions.push({
      title: `Synthetic Question ${i}`,
      slug: `synthetic-question-${i}`,
      difficulty,
      description: `Auto-generated placeholder problem #${i}. Implement solution to pass provided tests.`,
      examples: [`Example input -> output`],
      constraints: [`Input size up to 1000`],
      starterCode: {
        "C++": "#include <bits/stdc++.h>\nusing namespace std;\nint main() { return 0; }\n",
        Java: "class Solution { public static void main(String[] args) {} }",
        Python: "def solve():\n    pass\n\nif __name__ == '__main__':\n    solve()\n",
        JavaScript: "function solve() {\n  // implement\n}\nconsole.log('');",
      },
      supportedLanguages: ["C++", "Java", "Python", "JavaScript"],
      sampleTestCases: [{ input: "1", expectedOutput: "1", isHidden: false }],
      hiddenTestCases: [{ input: "2", expectedOutput: "2", isHidden: true }],
      timeLimit: 2000,
      memoryLimit: 256,
      tags: ["placeholder"],
    });
  }
}

appendPlaceholders(50);

async function seedQuestions() {
  try {
    await connectDB();
    await Question.collection.dropIndexes();
    await Question.deleteMany({});
    await Question.insertMany(questions);
    console.log(`Seeded ${questions.length} questions`);
    process.exit(0);
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

seedQuestions();
